defaults:
  - model: faster_rcnn
  - metrics: detection
  - datasets: ruler_detection_eval
  - dataloader: detection
  - transforms: detection
  - _self_

paths:
  images_dir: data/ruler/unlabeled
  coco_annotations: data/ruler/annotations/ruler_coco.json
  test_ids: data/ruler/annotations/split_test.txt

inferencer:
  device_tensors: ["images", "targets"]
  device: auto
  save_path: "inference_faster_rcnn"
  seed: 42
  from_pretrained: "saved/faster-rcnn/model_best.pth"
